# permissions for end users to view chessboards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chess-operator
    app.kubernetes.io/managed-by: kustomize
  name: chessboard-viewer-role
rules:
- apiGroups:
  - chess.k8s.io.my.domain
  resources:
  - chessboards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chess.k8s.io.my.domain
  resources:
  - chessboards/status
  verbs:
  - get
