# permissions for end users to edit chessais.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chess-operator
    app.kubernetes.io/managed-by: kustomize
  name: chessai-editor-role
rules:
- apiGroups:
  - chess.k8s.io.my.domain
  resources:
  - chessais
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chess.k8s.io.my.domain
  resources:
  - chessais/status
  verbs:
  - get
