name: GitHub Actions Demo
run-name: Lint
on:
  pull_request:
permissions:
  contents: read
env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.60
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}